language: python
cache:
    pip: true
    bunlder: true
    directories:
    - node_modules
matrix:
    include:
    - python: "3.6"

before_install:
    - echo "Installing Hugo 0.29, Node, and gulp"
    - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    - sudo apt install nodejs
    - wget https://github.com/gohugoio/hugo/releases/download/v0.30.2/hugo_0.30.2_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - sudo npm install --global gulp-cli
    - npm install

install:
    - echo "Install pytest and pip"
    - pip install -r ci/requirements.txt

before_script:
    - echo "Run as localhost"
    - gulp dev &
    - sleep 7

script:
    - echo "Running scripts"
    - python -m pytest

after:
    - echo "Print versions and skipped tests here"

