baseURL = "https://linode.com/docs/"
languageCode = "en-us"
title = "Linode Guides & Tutorials"

# Highlighting config (Pygments)

# Styles created with pygmentize -S perldoc -f html -a .highlight > syntax.css
# TODO(bep)
pygmentsUseClasses =  true
pygmentsCodeFences = true

# Use the new and fast Chroma highlighter (Pygments port) in Hugo 0.28.
pygmentsUseClassic = false

# See https://help.farbox.com/pygments.html
# Also see pygmentsUseClasses above.
pygmentsStyle = "perldoc"

disqusShortname="TODO"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
home = [ "HTML", "RSS"]
section = ["HTML"]
page = ["HTML"]

[taxonomies]
category = "categories"

[params]
description = "Guides and tutorials on the Linode platform, Linux basics, and software installation and configuration."
default_image_width = 120
default_image_height = 120

# Date and time formatting, see https://gohugo.io/functions/format/
time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
time_format_default = "Monday, January 2, 2006"


# Related Content ("See Also") configuration.
[related]
threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"